'use client';

import { useEffect, useState } from 'react';
import { useParams } from 'next/navigation';
import Link from 'next/link';
import { doc, getDoc } from 'firebase/firestore';
import { db } from '@/lib/firebase';
import { Check, Clock, Sparkles, AlertCircle } from 'lucide-react';
import type { QuoteAnalysis, ServiceRecommendation } from '@/types/ai';

interface QuoteData {
    type: 'lens' | 'smart_quote';
    data: QuoteAnalysis | ServiceRecommendation;
    createdAt: any;
    salonName?: string;
}

export default function PublicQuote() {
    const params = useParams();
    const id = params?.id as string;
    const [quote, setQuote] = useState<QuoteData | null>(null);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState<string | null>(null);

    useEffect(() => {
        const fetchQuote = async () => {
            if (!id) return;
            try {
                const docRef = doc(db, 'quotes', id);
                const docSnap = await getDoc(docRef);

                if (docSnap.exists()) {
                    setQuote(docSnap.data() as QuoteData);
                } else {
                    setError("Quote not found.");
                }
            } catch (err) {
                console.error("Error fetching quote:", err);
                setError("Could not load quote.");
            } finally {
                setLoading(false);
            }
        };

        fetchQuote();
    }, [id]);

    if (loading) {
        return (
            <div className="min-h-screen bg-pink-50 flex items-center justify-center">
                <div className="animate-pulse flex flex-col items-center">
                    <div className="w-12 h-12 bg-pink-200 rounded-full mb-4"></div>
                    <div className="h-4 w-32 bg-pink-200 rounded"></div>
                </div>
            </div>
        );
    }

    if (error || !quote) {
        return (
            <div className="min-h-screen bg-pink-50 flex items-center justify-center p-4">
                <div className="bg-white p-8 rounded-3xl shadow-xl text-center max-w-md w-full">
                    <AlertCircle size={48} className="mx-auto text-pink-300 mb-4" />
                    <h1 className="text-2xl font-bold text-charcoal mb-2">Quote Not Found</h1>
                    <p className="text-gray-600 mb-6">{error || "This link might be expired or invalid."}</p>
                    <Link href="/" className="inline-block bg-charcoal text-white px-6 py-3 rounded-xl font-bold hover:bg-black transition-colors">
                        Go to Lacqr
                    </Link>
                </div>
            </div>
        );
    }

    const isLens = quote.type === 'lens';
    const lensData = quote.data as QuoteAnalysis;
    const smartData = quote.data as ServiceRecommendation;

    return (
        <div className="min-h-screen bg-pink-50 py-12 px-4">
            <div className="max-w-md mx-auto space-y-6">
                {/* Header */}
                <div className="text-center">
                    <div className="inline-flex items-center justify-center w-12 h-12 bg-black text-white rounded-xl font-display font-bold text-xl mb-4">
                        L.
                    </div>
                    <h1 className="text-2xl font-bold text-charcoal font-display">
                        {quote.salonName || "Your Nail Tech"} sent you a quote
                    </h1>
                    <p className="text-gray-500 text-sm mt-1">
                        Generated by Lacqr AI
                    </p>
                </div>

                {/* Quote Card */}
                <div className="bg-white rounded-3xl shadow-xl overflow-hidden border border-pink-100">
                    <div className="bg-charcoal text-white p-6 text-center">
                        <p className="text-xs uppercase tracking-wider font-bold text-gray-400 mb-1">Estimated Total</p>
                        <div className="text-5xl font-bold font-display">
                            {isLens ? `$${lensData.total_estimated_price}` : 'Custom Quote'}
                        </div>
                    </div>

                    <div className="p-6 space-y-6">
                        {isLens ? (
                            // Lacqr Lens Breakdown
                            <div className="space-y-4">
                                <div className="flex justify-between items-center py-2 border-b border-gray-100">
                                    <span className="font-bold text-charcoal">{lensData.breakdown.base_service.name}</span>
                                    <span className="font-bold">${lensData.breakdown.base_service.price}</span>
                                </div>
                                {lensData.breakdown.add_ons.map((addon, i) => (
                                    <div key={i} className="flex justify-between items-center py-2 border-b border-gray-100 last:border-0">
                                        <div className="flex items-center">
                                            <span className="text-gray-600">{addon.name}</span>
                                            {addon.count > 1 && (
                                                <span className="ml-2 bg-gray-100 text-gray-500 text-[10px] px-1.5 py-0.5 rounded-full font-bold">
                                                    x{addon.count}
                                                </span>
                                            )}
                                        </div>
                                        <span className="font-medium text-gray-900">${addon.estimated_price}</span>
                                    </div>
                                ))}
                            </div>
                        ) : (
                            // Smart Quote Breakdown
                            <div className="space-y-4">
                                <div className="bg-pink-50 p-4 rounded-xl">
                                    <h3 className="font-bold text-pink-900 mb-2 flex items-center">
                                        <Sparkles size={16} className="mr-2" />
                                        Recommended Booking
                                    </h3>
                                    <div className="space-y-2">
                                        {smartData.booking_codes.map((code, i) => (
                                            <div key={i} className="flex items-center text-pink-800">
                                                <Check size={14} className="mr-2" />
                                                {code}
                                            </div>
                                        ))}
                                    </div>
                                </div>
                                <div className="flex items-center text-gray-600 justify-center">
                                    <Clock size={16} className="mr-2" />
                                    <span>Est. Duration: {smartData.estimated_duration_minutes} mins</span>
                                </div>
                            </div>
                        )}

                        {/* AI Note */}
                        {(isLens ? lensData.visual_description : smartData.reasoning) && (
                            <div className="bg-gray-50 p-4 rounded-xl text-sm text-gray-600 italic">
                                &quot;{isLens ? lensData.visual_description : smartData.reasoning}&quot;
                            </div>
                        )}
                    </div>

                    {/* Footer Actions */}
                    <div className="p-6 bg-gray-50 border-t border-gray-100 text-center">
                        <button className="w-full bg-pink-500 text-white py-4 rounded-xl font-bold hover:bg-pink-600 transition-colors shadow-lg shadow-pink-200 mb-3">
                            Book This Look
                        </button>
                        <p className="text-xs text-gray-400">
                            *Final price may vary based on actual service time and additional requests.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    );
}
