import type { QuoteAnalysis } from '../types/ai';

export const generateReceipt = async (analysis: QuoteAnalysis, salonName: string = "Lacqr Studio"): Promise<string> => {
    const canvas = document.createElement('canvas');
    const ctx = canvas.getContext('2d');
    if (!ctx) throw new Error('Could not get canvas context');

    // Set dimensions (Receipt style: narrow and long)
    const width = 600;
    // Calculate height based on items
    const headerHeight = 200;
    const itemHeight = 50;
    const footerHeight = 150;
    const itemsCount = 1 + analysis.breakdown.add_ons.length; // Base service + addons
    const height = headerHeight + (itemsCount * itemHeight) + footerHeight;

    canvas.width = width;
    canvas.height = height;

    // Background
    ctx.fillStyle = '#ffffff';
    ctx.fillRect(0, 0, width, height);

    // Header
    ctx.fillStyle = '#000000';
    ctx.font = 'bold 40px serif';
    ctx.textAlign = 'center';
    ctx.fillText(salonName, width / 2, 80);

    ctx.font = '20px sans-serif';
    ctx.fillStyle = '#666666';
    ctx.fillText('Official Receipt', width / 2, 120);

    const date = new Date().toLocaleDateString();
    const time = new Date().toLocaleTimeString();
    ctx.font = '16px sans-serif';
    ctx.fillText(`${date} • ${time}`, width / 2, 150);

    // Divider
    ctx.beginPath();
    ctx.moveTo(50, 180);
    ctx.lineTo(550, 180);
    ctx.strokeStyle = '#eeeeee';
    ctx.lineWidth = 2;
    ctx.stroke();

    // Items
    let currentY = 240;
    ctx.textAlign = 'left';

    // Base Service
    ctx.font = 'bold 24px sans-serif';
    ctx.fillStyle = '#000000';
    ctx.fillText(analysis.breakdown.base_service.name, 50, currentY);

    ctx.textAlign = 'right';
    ctx.fillText(`$${analysis.breakdown.base_service.price.toFixed(2)}`, 550, currentY);

    currentY += itemHeight;

    // Add-ons
    ctx.font = '20px sans-serif';
    ctx.fillStyle = '#444444';

    analysis.breakdown.add_ons.forEach(addon => {
        ctx.textAlign = 'left';
        const name = addon.count > 1 ? `${addon.name} (x${addon.count})` : addon.name;
        ctx.fillText(name, 50, currentY);

        ctx.textAlign = 'right';
        ctx.fillText(`$${addon.estimated_price.toFixed(2)}`, 550, currentY);
        currentY += itemHeight;
    });

    // Divider
    currentY += 20;
    ctx.beginPath();
    ctx.moveTo(50, currentY);
    ctx.lineTo(550, currentY);
    ctx.stroke();

    // Total
    currentY += 60;
    ctx.textAlign = 'left';
    ctx.font = 'bold 32px sans-serif';
    ctx.fillStyle = '#000000';
    ctx.fillText('TOTAL', 50, currentY);

    ctx.textAlign = 'right';
    ctx.fillStyle = '#ec4899'; // Pink-500
    ctx.fillText(`$${analysis.total_estimated_price.toFixed(2)}`, 550, currentY);

    // Footer
    currentY += 80;
    ctx.textAlign = 'center';
    ctx.font = 'italic 16px serif';
    ctx.fillStyle = '#888888';
    ctx.fillText('Thank you for your business!', width / 2, currentY);

    ctx.font = '12px sans-serif';
    ctx.fillStyle = '#aaaaaa';
    ctx.fillText('Generated by Lacqr', width / 2, currentY + 30);

    return canvas.toDataURL('image/png');
};
